#!/usr/bin/env python3
"""Deterministically (re)generate tls/manifest.txt: the list of application
message sizes the `tls_framed` scenario transfers, one per line, in bytes.

Every arm's framed server reads this file and sends exactly these N messages
(length-prefixed) in order; every arm's framed client reads it to know how many
messages and how many bytes to expect. Like gen_payload.sh, the point is that
"reproducible" means "check the hash": fixed distribution, fixed N, fixed seed,
fixed target volume -> byte-identical manifest on every machine.

W1 micro-picks (design doc, agreed 2026-09-08):
  - shape: the Facebook Hadoop message-size distribution (Homa, Montazeri et al.,
    SIGCOMM 2018, workload "W1"; also used by pFabric/Homa simulators). Wide and
    bimodal: many small control-sized messages, a heavy tail of large blocks.
  - N = 10000 messages.
  - target volume: the N messages are linearly rescaled to sum to ~100 MiB, the
    same transfer volume as the streaming payload, so tls_framed time/energy sit
    on the same scale as the other scenarios. Only the absolute size axis moves;
    the heavy-tail shape (ratios, bimodality) is preserved.
  - tail cap: no single message may exceed --cap bytes (default 5 % of the target
    volume). At the default scale nothing reaches it; it is a guard for other
    scales.

  NOTE: the _W1_CDF table below is a piecewise approximation of W1 entered by
  hand. Before the paper run it must be replaced with the exact published points
  (Homa Figure 2 / its released workload files). The knobs (N, target volume,
  seed) and the manifest format are final; only the _W1_CDF numbers are
  provisional.

  tls/gen_manifest.py [--n N] [--target-mib M] [--cap BYTES] [--seed S] [--out PATH]
"""

import argparse
import bisect
import hashlib
import math
import random
import sys
from pathlib import Path

# (size_bytes, cumulative_probability). Piecewise; interpolated log-linear in
# size against linear cumulative probability. PROVISIONAL -- see module docstring.
_W1_CDF = [
    (10,          0.00),
    (100,         0.15),
    (300,         0.30),
    (1_000,       0.48),
    (3_000,       0.60),
    (10_000,      0.70),
    (30_000,      0.78),
    (100_000,     0.86),
    (300_000,     0.91),
    (1_000_000,   0.96),
    (3_000_000,   0.99),
    (10_000_000,  1.00),
]

DEFAULT_N = 10_000
DEFAULT_TARGET_MIB = 100.0
DEFAULT_SEED = 20260908
MIN_SIZE = 4  # never emit 0: a zero-length frame collides with the EOF sentinel


def _sample_shape(u: float) -> float:
    """Inverse-CDF sample for a uniform u in [0, 1), log-linear interpolation."""
    probs = [p for _, p in _W1_CDF]
    i = bisect.bisect_right(probs, u)
    if i <= 0:
        return float(_W1_CDF[0][0])
    if i >= len(_W1_CDF):
        return float(_W1_CDF[-1][0])
    s0, p0 = _W1_CDF[i - 1]
    s1, p1 = _W1_CDF[i]
    if p1 <= p0:
        return float(s0)
    frac = (u - p0) / (p1 - p0)
    return math.exp(math.log(s0) + frac * (math.log(s1) - math.log(s0)))


def generate(n: int, target_bytes: int, cap: int, seed: int) -> list[int]:
    rng = random.Random(seed)
    raw = [_sample_shape(rng.random()) for _ in range(n)]

    # Linearly rescale the size axis so the N messages sum to the target volume,
    # then clamp to [MIN_SIZE, cap]. Clamping perturbs the total by well under a
    # percent at the default scale (only the extreme tail is clipped).
    raw_total = sum(raw)
    factor = target_bytes / raw_total if raw_total > 0 else 1.0
    return [max(MIN_SIZE, min(int(round(s * factor)), cap)) for s in raw]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=DEFAULT_N)
    ap.add_argument("--target-mib", type=float, default=DEFAULT_TARGET_MIB,
                    help="total transfer volume the N messages sum to (MiB)")
    ap.add_argument("--cap", type=int, default=0,
                    help="per-message byte cap; 0 => 5%% of the target volume")
    ap.add_argument("--seed", type=int, default=DEFAULT_SEED)
    ap.add_argument("--out", type=Path,
                    default=Path(__file__).resolve().parent / "manifest.txt")
    args = ap.parse_args()

    target_bytes = int(round(args.target_mib * 1024 * 1024))
    cap = args.cap if args.cap > 0 else max(MIN_SIZE, target_bytes // 20)

    sizes = generate(args.n, target_bytes, cap, args.seed)
    total = sum(sizes)

    header = (
        f"# tls_framed message-size manifest -- generated by tls/gen_manifest.py\n"
        f"# shape=facebook-hadoop-W1(provisional) n={args.n} "
        f"target_mib={args.target_mib} cap={cap} seed={args.seed}\n"
        f"# messages={len(sizes)} total_bytes={total} "
        f"min={min(sizes)} max={max(sizes)} mean={total // len(sizes)}\n"
    )
    text = header + "\n".join(str(s) for s in sizes) + "\n"
    args.out.write_text(text)

    digest = hashlib.sha256(text.encode()).hexdigest()
    print(f"tls/gen_manifest.py: {args.out}")
    print(f"  messages={len(sizes)} total_bytes={total} "
          f"({total / 1024 / 1024:.1f} MiB) min={min(sizes)} "
          f"max={max(sizes)} mean={total // len(sizes)}")
    print(f"  sha256={digest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
